### ISSUE TITLE
SVG Icon pack not rendering :(

### ISSUE THREAD

**Issue by JhonnyRice** [joniv2/rofi#2]
Ok so, apparently my icons arent showing when I do `rofi -show run`. I am with the `default` theme and Reversal-Green Icon Pack

**Comment by JhonnyRice** [comment]
When I tried to do `rofi -show drun -drun-show-icons` I got this error:

`(process:2315): Helpers.IconFetcher-WARNING **: 17:08:24.471: Failed to load image: Couldn’t recognize the image file format for file “/home/user/.local/share/icons/Reversal-green-dark/apps/scalable/applications-system.svg”`

**Comment by JhonnyRice** [comment]
found out that Rofi used a package called `pkg-pixbuf`, that usually has the `svg` file support, but for some reason, the one used by rofi doesn't have it. This are the file formats supported by rofi:
```
png
jpeg
jpe
jpg
ani
bmp
gif
icns
ico
cur
pnm
pbm
pgm
ppm
qtif
qif
tga
targa
xbm
xpm

```
and this are the ones supported by classic pixbuf:
```

    ani
    bmp
    GdkPixdata
    gif
    icns
    ico
    jpeg
    png
    pnm
    qtif
    svg
    tga
    tiff
    wmf
    xbm
    xpm

```

**Comment by JhonnyRice** [comment]
So to add the svg support I need a thing called `librsvg`. But after installing it, it still gave me the same error
Please help

**Comment by joniv2** [comment]
hmmm, this hasn't happened to me before. Maybe double check the icon theme name and try installing it system-wide. if this doesn't fix it, soon I'll be rewriting all the themes from scratch optimizing and making the config more modular.

**Comment by joniv2** [comment]
> Ok so, apparently my icons arent showing when I do rofi -show run. I am with the default theme and Reversal-Green Icon Pack

the icons are only shown in drun mode, just execute rofi cause the modi is set up in configuration file.

**Comment by joniv2** [comment]
since I forgot to mention could you give the following information?
distro
rofi version

this could help into finding other problems which may lead to the breakage of rofi

**Comment by JhonnyRice** [comment]
Distro: Kubuntu 20.04 LTS
Rofi 1.6.1

**Comment by JhonnyRice** [comment]
hope this helps

**Comment by JhonnyRice** [comment]
It doesn't work in drun mode either tho. try to reinstall the icon pack
